apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.element.serviceName }}
  labels:
    app: element
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.element.port }}
      targetPort: {{ .Values.element.port }}
      protocol: TCP
      name: http
  selector:
    app: element
