apiVersion: v1
kind: ConfigMap
metadata:
  name: element-nginx-config
data:
  default.conf: |
    server {
        listen       8080;
        listen  [::]:8080;
        server_name  www.riot.test.savannahghi.org riot.test.savannahghi.org;

        root   /usr/share/nginx/html;
        index  index.html;

{{ .Values.nginxConfig | indent 8 }}

        # Set no-cache for the index.html only so that browsers always check for a new copy of Element Web.
        location = /index.html {
            add_header Cache-Control "no-cache";
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
    }
