apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "matrix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configuration.yaml") . | sha256sum }}
        checksum/config-nginx: {{ include (print .Template.BasePath "/configuration-nginx.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "matrix.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: element
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.element.image.repository }}:{{ .Values.element.image.tag }}"
          imagePullPolicy: {{ .Values.element.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.element.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
          - name: {{ .Values.element.configSecretName }}
            mountPath: {{ .Values.element.configmountpath }}
            subPath: config.json

          - mountPath: /etc/nginx/conf.d
            name: config-nginx
          
      volumes:
      - name: {{ .Values.element.configSecretName }}
        configMap:
          name: {{ .Values.element.configSecretName }}
      
      - name: config-nginx
        configMap:
          name: element-nginx-config