apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.synapse.port }}
      targetPort: {{ .Values.synapse.port }}
      protocol: TCP
      name: http
      
    {{- if .Values.synapse.metrics.enabled }}
    - port: {{ .Values.synapse.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "matrix.selectorLabels" . | nindent 4 }}
